"""Update IV

Revision ID: 99bb32a20bf9
Revises: 
Create Date: 2026-01-19 21:14:55.797640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bb32a20bf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('conversation_key_encrypted_for_receiver', sa.Text(), nullable=False),
    sa.Column('conversation_key_encrypted_for_sender', sa.Text(), nullable=False),
    sa.Column('sender_iv', sa.String(length=24), nullable=False),
    sa.Column('receiver_iv', sa.String(length=24), nullable=True),
    sa.Column('signature_for_receiver', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name='valid_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', 'status', name='unique_pending_request')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('encryption_iv',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('encryption_iv',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_requests_status'))

    op.drop_table('friend_requests')
    # ### end Alembic commands ###
